//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Project/Scripts/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Bit"",
            ""id"": ""72aa216c-111b-4548-94a7-f136e37e64fb"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""3614ceaf-8081-40bd-bd3b-dcfcd99edd1f"",
                    ""expectedControlType"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""80781d00-0f79-4a07-83f7-6c4bea702451"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapColor"",
                    ""type"": ""Button"",
                    ""id"": ""f288fc6f-ccfd-4bb7-a4bf-da595603cc10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Stick"",
                    ""id"": ""bb4f153f-8dae-4504-bb74-7dabae3d3bcd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2b86f75a-3e2b-40dc-be22-2ae8c15f759d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e1dd32a1-9f62-44cc-ac42-7619389a8668"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""eeffe273-f8a7-40e6-b3c2-b6ccc2f8ba02"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8cd5d279-770c-4e28-9649-4606e1a91780"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e07b1ed0-e2da-4882-a7a1-138ba46e7ef4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1390c8e3-d80a-4897-a670-c61824019c88"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2bb36e4-84a8-4ac3-be51-e9dab3df0547"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""331f1a03-ec33-49c4-87c1-af93c55ed72c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36e8126f-d29a-4cb1-9389-2e6ce7c5116f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level"",
            ""id"": ""55b2818e-74b3-4e1a-9bcf-fa083cc50957"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""3fef811b-a766-491a-991e-8eb2257ad706"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""82d06404-63c6-4fef-abf0-c5e910ffb587"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ab25e21-69f5-432e-8b42-1032355e40a2"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bit
        m_Bit = asset.FindActionMap("Bit", throwIfNotFound: true);
        m_Bit_Walk = m_Bit.FindAction("Walk", throwIfNotFound: true);
        m_Bit_Jump = m_Bit.FindAction("Jump", throwIfNotFound: true);
        m_Bit_SwapColor = m_Bit.FindAction("SwapColor", throwIfNotFound: true);
        // Level
        m_Level = asset.FindActionMap("Level", throwIfNotFound: true);
        m_Level_Restart = m_Level.FindAction("Restart", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bit
    private readonly InputActionMap m_Bit;
    private IBitActions m_BitActionsCallbackInterface;
    private readonly InputAction m_Bit_Walk;
    private readonly InputAction m_Bit_Jump;
    private readonly InputAction m_Bit_SwapColor;
    public struct BitActions
    {
        private @PlayerInputs m_Wrapper;
        public BitActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_Bit_Walk;
        public InputAction @Jump => m_Wrapper.m_Bit_Jump;
        public InputAction @SwapColor => m_Wrapper.m_Bit_SwapColor;
        public InputActionMap Get() { return m_Wrapper.m_Bit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BitActions set) { return set.Get(); }
        public void SetCallbacks(IBitActions instance)
        {
            if (m_Wrapper.m_BitActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_BitActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_BitActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_BitActionsCallbackInterface.OnWalk;
                @Jump.started -= m_Wrapper.m_BitActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_BitActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_BitActionsCallbackInterface.OnJump;
                @SwapColor.started -= m_Wrapper.m_BitActionsCallbackInterface.OnSwapColor;
                @SwapColor.performed -= m_Wrapper.m_BitActionsCallbackInterface.OnSwapColor;
                @SwapColor.canceled -= m_Wrapper.m_BitActionsCallbackInterface.OnSwapColor;
            }
            m_Wrapper.m_BitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @SwapColor.started += instance.OnSwapColor;
                @SwapColor.performed += instance.OnSwapColor;
                @SwapColor.canceled += instance.OnSwapColor;
            }
        }
    }
    public BitActions @Bit => new BitActions(this);

    // Level
    private readonly InputActionMap m_Level;
    private ILevelActions m_LevelActionsCallbackInterface;
    private readonly InputAction m_Level_Restart;
    public struct LevelActions
    {
        private @PlayerInputs m_Wrapper;
        public LevelActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_Level_Restart;
        public InputActionMap Get() { return m_Wrapper.m_Level; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LevelActions set) { return set.Get(); }
        public void SetCallbacks(ILevelActions instance)
        {
            if (m_Wrapper.m_LevelActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_LevelActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_LevelActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_LevelActionsCallbackInterface.OnRestart;
            }
            m_Wrapper.m_LevelActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }
        }
    }
    public LevelActions @Level => new LevelActions(this);
    public interface IBitActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSwapColor(InputAction.CallbackContext context);
    }
    public interface ILevelActions
    {
        void OnRestart(InputAction.CallbackContext context);
    }
}
